// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryPoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NumericMetrics map[string]float64     `protobuf:"bytes,2,rep,name=numeric_metrics,json=numericMetrics,proto3" json:"numeric_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StringMetrics  map[string]string      `protobuf:"bytes,3,rep,name=string_metrics,json=stringMetrics,proto3" json:"string_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BooleanMetrics map[string]bool        `protobuf:"bytes,4,rep,name=boolean_metrics,json=booleanMetrics,proto3" json:"boolean_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelemetryPoint) Reset() {
	*x = TelemetryPoint{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPoint) ProtoMessage() {}

func (x *TelemetryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPoint.ProtoReflect.Descriptor instead.
func (*TelemetryPoint) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TelemetryPoint) GetNumericMetrics() map[string]float64 {
	if x != nil {
		return x.NumericMetrics
	}
	return nil
}

func (x *TelemetryPoint) GetStringMetrics() map[string]string {
	if x != nil {
		return x.StringMetrics
	}
	return nil
}

func (x *TelemetryPoint) GetBooleanMetrics() map[string]bool {
	if x != nil {
		return x.BooleanMetrics
	}
	return nil
}

type GetLatestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Metrics       []string               `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`                                     // список метрик (опционально)
	MaxAgeSeconds int32                  `protobuf:"varint,3,opt,name=max_age_seconds,json=maxAgeSeconds,proto3" json:"max_age_seconds,omitempty"` // максимальный возраст данных
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestRequest) Reset() {
	*x = GetLatestRequest{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRequest) ProtoMessage() {}

func (x *GetLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRequest.ProtoReflect.Descriptor instead.
func (*GetLatestRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *GetLatestRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetLatestRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetLatestRequest) GetMaxAgeSeconds() int32 {
	if x != nil {
		return x.MaxAgeSeconds
	}
	return 0
}

type GetLatestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Data          *TelemetryPoint        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	FromCache     bool                   `protobuf:"varint,3,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestResponse) Reset() {
	*x = GetLatestResponse{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestResponse) ProtoMessage() {}

func (x *GetLatestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestResponse.ProtoReflect.Descriptor instead.
func (*GetLatestResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *GetLatestResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetLatestResponse) GetData() *TelemetryPoint {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetLatestResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Metrics       []string               `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetHistoryRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetHistoryRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetHistoryRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Points        []*TelemetryPoint      `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetHistoryResponse) GetPoints() []*TelemetryPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *GetHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WriteTelemetryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NumericMetrics map[string]float64     `protobuf:"bytes,3,rep,name=numeric_metrics,json=numericMetrics,proto3" json:"numeric_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StringMetrics  map[string]string      `protobuf:"bytes,4,rep,name=string_metrics,json=stringMetrics,proto3" json:"string_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BooleanMetrics map[string]bool        `protobuf:"bytes,5,rep,name=boolean_metrics,json=booleanMetrics,proto3" json:"boolean_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Source         string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"` // "device", "integration", "simulator"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteTelemetryRequest) Reset() {
	*x = WriteTelemetryRequest{}
	mi := &file_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTelemetryRequest) ProtoMessage() {}

func (x *WriteTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTelemetryRequest.ProtoReflect.Descriptor instead.
func (*WriteTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *WriteTelemetryRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *WriteTelemetryRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WriteTelemetryRequest) GetNumericMetrics() map[string]float64 {
	if x != nil {
		return x.NumericMetrics
	}
	return nil
}

func (x *WriteTelemetryRequest) GetStringMetrics() map[string]string {
	if x != nil {
		return x.StringMetrics
	}
	return nil
}

func (x *WriteTelemetryRequest) GetBooleanMetrics() map[string]bool {
	if x != nil {
		return x.BooleanMetrics
	}
	return nil
}

func (x *WriteTelemetryRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type WriteTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PointsWritten int32                  `protobuf:"varint,2,opt,name=points_written,json=pointsWritten,proto3" json:"points_written,omitempty"`
	Alerts        []string               `protobuf:"bytes,3,rep,name=alerts,proto3" json:"alerts,omitempty"` // сработавшие алерты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTelemetryResponse) Reset() {
	*x = WriteTelemetryResponse{}
	mi := &file_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTelemetryResponse) ProtoMessage() {}

func (x *WriteTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTelemetryResponse.ProtoReflect.Descriptor instead.
func (*WriteTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *WriteTelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteTelemetryResponse) GetPointsWritten() int32 {
	if x != nil {
		return x.PointsWritten
	}
	return 0
}

func (x *WriteTelemetryResponse) GetAlerts() []string {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ttelemetry\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x97\x04\n" +
	"\x0eTelemetryPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12V\n" +
	"\x0fnumeric_metrics\x18\x02 \x03(\v2-.telemetry.TelemetryPoint.NumericMetricsEntryR\x0enumericMetrics\x12S\n" +
	"\x0estring_metrics\x18\x03 \x03(\v2,.telemetry.TelemetryPoint.StringMetricsEntryR\rstringMetrics\x12V\n" +
	"\x0fboolean_metrics\x18\x04 \x03(\v2-.telemetry.TelemetryPoint.BooleanMetricsEntryR\x0ebooleanMetrics\x1aA\n" +
	"\x13NumericMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a@\n" +
	"\x12StringMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13BooleanMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"q\n" +
	"\x10GetLatestRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\ametrics\x18\x02 \x03(\tR\ametrics\x12&\n" +
	"\x0fmax_age_seconds\x18\x03 \x01(\x05R\rmaxAgeSeconds\"~\n" +
	"\x11GetLatestResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12-\n" +
	"\x04data\x18\x02 \x01(\v2\x19.telemetry.TelemetryPointR\x04data\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x03 \x01(\bR\tfromCache\"\xbc\x01\n" +
	"\x11GetHistoryRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x18\n" +
	"\ametrics\x18\x04 \x03(\tR\ametrics\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"z\n" +
	"\x12GetHistoryResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x121\n" +
	"\x06points\x18\x02 \x03(\v2\x19.telemetry.TelemetryPointR\x06points\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\xe8\x04\n" +
	"\x15WriteTelemetryRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12]\n" +
	"\x0fnumeric_metrics\x18\x03 \x03(\v24.telemetry.WriteTelemetryRequest.NumericMetricsEntryR\x0enumericMetrics\x12Z\n" +
	"\x0estring_metrics\x18\x04 \x03(\v23.telemetry.WriteTelemetryRequest.StringMetricsEntryR\rstringMetrics\x12]\n" +
	"\x0fboolean_metrics\x18\x05 \x03(\v24.telemetry.WriteTelemetryRequest.BooleanMetricsEntryR\x0ebooleanMetrics\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x1aA\n" +
	"\x13NumericMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a@\n" +
	"\x12StringMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13BooleanMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"q\n" +
	"\x16WriteTelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0epoints_written\x18\x02 \x01(\x05R\rpointsWritten\x12\x16\n" +
	"\x06alerts\x18\x03 \x03(\tR\x06alerts2\x8e\x02\n" +
	"\x10TelemetryService\x12O\n" +
	"\x12GetLatestTelemetry\x12\x1b.telemetry.GetLatestRequest\x1a\x1c.telemetry.GetLatestResponse\x12R\n" +
	"\x13GetTelemetryHistory\x12\x1c.telemetry.GetHistoryRequest\x1a\x1d.telemetry.GetHistoryResponse\x12U\n" +
	"\x0eWriteTelemetry\x12 .telemetry.WriteTelemetryRequest\x1a!.telemetry.WriteTelemetryResponseB\x1dZ\x1b./proto/telemetry;telemetryb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_telemetry_proto_goTypes = []any{
	(*TelemetryPoint)(nil),         // 0: telemetry.TelemetryPoint
	(*GetLatestRequest)(nil),       // 1: telemetry.GetLatestRequest
	(*GetLatestResponse)(nil),      // 2: telemetry.GetLatestResponse
	(*GetHistoryRequest)(nil),      // 3: telemetry.GetHistoryRequest
	(*GetHistoryResponse)(nil),     // 4: telemetry.GetHistoryResponse
	(*WriteTelemetryRequest)(nil),  // 5: telemetry.WriteTelemetryRequest
	(*WriteTelemetryResponse)(nil), // 6: telemetry.WriteTelemetryResponse
	nil,                            // 7: telemetry.TelemetryPoint.NumericMetricsEntry
	nil,                            // 8: telemetry.TelemetryPoint.StringMetricsEntry
	nil,                            // 9: telemetry.TelemetryPoint.BooleanMetricsEntry
	nil,                            // 10: telemetry.WriteTelemetryRequest.NumericMetricsEntry
	nil,                            // 11: telemetry.WriteTelemetryRequest.StringMetricsEntry
	nil,                            // 12: telemetry.WriteTelemetryRequest.BooleanMetricsEntry
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
}
var file_telemetry_proto_depIdxs = []int32{
	13, // 0: telemetry.TelemetryPoint.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 1: telemetry.TelemetryPoint.numeric_metrics:type_name -> telemetry.TelemetryPoint.NumericMetricsEntry
	8,  // 2: telemetry.TelemetryPoint.string_metrics:type_name -> telemetry.TelemetryPoint.StringMetricsEntry
	9,  // 3: telemetry.TelemetryPoint.boolean_metrics:type_name -> telemetry.TelemetryPoint.BooleanMetricsEntry
	0,  // 4: telemetry.GetLatestResponse.data:type_name -> telemetry.TelemetryPoint
	13, // 5: telemetry.GetHistoryRequest.from:type_name -> google.protobuf.Timestamp
	13, // 6: telemetry.GetHistoryRequest.to:type_name -> google.protobuf.Timestamp
	0,  // 7: telemetry.GetHistoryResponse.points:type_name -> telemetry.TelemetryPoint
	13, // 8: telemetry.WriteTelemetryRequest.timestamp:type_name -> google.protobuf.Timestamp
	10, // 9: telemetry.WriteTelemetryRequest.numeric_metrics:type_name -> telemetry.WriteTelemetryRequest.NumericMetricsEntry
	11, // 10: telemetry.WriteTelemetryRequest.string_metrics:type_name -> telemetry.WriteTelemetryRequest.StringMetricsEntry
	12, // 11: telemetry.WriteTelemetryRequest.boolean_metrics:type_name -> telemetry.WriteTelemetryRequest.BooleanMetricsEntry
	1,  // 12: telemetry.TelemetryService.GetLatestTelemetry:input_type -> telemetry.GetLatestRequest
	3,  // 13: telemetry.TelemetryService.GetTelemetryHistory:input_type -> telemetry.GetHistoryRequest
	5,  // 14: telemetry.TelemetryService.WriteTelemetry:input_type -> telemetry.WriteTelemetryRequest
	2,  // 15: telemetry.TelemetryService.GetLatestTelemetry:output_type -> telemetry.GetLatestResponse
	4,  // 16: telemetry.TelemetryService.GetTelemetryHistory:output_type -> telemetry.GetHistoryResponse
	6,  // 17: telemetry.TelemetryService.WriteTelemetry:output_type -> telemetry.WriteTelemetryResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
