// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: automation.proto

package automation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConditionType int32

const (
	ConditionType_DEVICE_STATE ConditionType = 0
	ConditionType_TIME         ConditionType = 1
	ConditionType_TELEMETRY    ConditionType = 2
	ConditionType_AND          ConditionType = 3
	ConditionType_OR           ConditionType = 4
	ConditionType_NOT          ConditionType = 5
	ConditionType_SUN          ConditionType = 6
)

// Enum value maps for ConditionType.
var (
	ConditionType_name = map[int32]string{
		0: "DEVICE_STATE",
		1: "TIME",
		2: "TELEMETRY",
		3: "AND",
		4: "OR",
		5: "NOT",
		6: "SUN",
	}
	ConditionType_value = map[string]int32{
		"DEVICE_STATE": 0,
		"TIME":         1,
		"TELEMETRY":    2,
		"AND":          3,
		"OR":           4,
		"NOT":          5,
		"SUN":          6,
	}
)

func (x ConditionType) Enum() *ConditionType {
	p := new(ConditionType)
	*p = x
	return p
}

func (x ConditionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionType) Descriptor() protoreflect.EnumDescriptor {
	return file_automation_proto_enumTypes[0].Descriptor()
}

func (ConditionType) Type() protoreflect.EnumType {
	return &file_automation_proto_enumTypes[0]
}

func (x ConditionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionType.Descriptor instead.
func (ConditionType) EnumDescriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{0}
}

type ActionType int32

const (
	ActionType_DEVICE_COMMAND ActionType = 0
	ActionType_NOTIFICATION   ActionType = 1
	ActionType_DELAY          ActionType = 2
	ActionType_WEBHOOK        ActionType = 3
	ActionType_SCENE          ActionType = 4
	ActionType_PARALLEL       ActionType = 5
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "DEVICE_COMMAND",
		1: "NOTIFICATION",
		2: "DELAY",
		3: "WEBHOOK",
		4: "SCENE",
		5: "PARALLEL",
	}
	ActionType_value = map[string]int32{
		"DEVICE_COMMAND": 0,
		"NOTIFICATION":   1,
		"DELAY":          2,
		"WEBHOOK":        3,
		"SCENE":          4,
		"PARALLEL":       5,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_automation_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_automation_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{1}
}

type ComparisonOperator int32

const (
	ComparisonOperator_EQ  ComparisonOperator = 0
	ComparisonOperator_NE  ComparisonOperator = 1
	ComparisonOperator_GT  ComparisonOperator = 2
	ComparisonOperator_LT  ComparisonOperator = 3
	ComparisonOperator_GTE ComparisonOperator = 4
	ComparisonOperator_LTE ComparisonOperator = 5
)

// Enum value maps for ComparisonOperator.
var (
	ComparisonOperator_name = map[int32]string{
		0: "EQ",
		1: "NE",
		2: "GT",
		3: "LT",
		4: "GTE",
		5: "LTE",
	}
	ComparisonOperator_value = map[string]int32{
		"EQ":  0,
		"NE":  1,
		"GT":  2,
		"LT":  3,
		"GTE": 4,
		"LTE": 5,
	}
)

func (x ComparisonOperator) Enum() *ComparisonOperator {
	p := new(ComparisonOperator)
	*p = x
	return p
}

func (x ComparisonOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComparisonOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_automation_proto_enumTypes[2].Descriptor()
}

func (ComparisonOperator) Type() protoreflect.EnumType {
	return &file_automation_proto_enumTypes[2]
}

func (x ComparisonOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComparisonOperator.Descriptor instead.
func (ComparisonOperator) EnumDescriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{2}
}

type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ConditionType          `protobuf:"varint,2,opt,name=type,proto3,enum=automation.ConditionType" json:"type,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Property      string                 `protobuf:"bytes,4,opt,name=property,proto3" json:"property,omitempty"`
	Operator      ComparisonOperator     `protobuf:"varint,5,opt,name=operator,proto3,enum=automation.ComparisonOperator" json:"operator,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Cron          string                 `protobuf:"bytes,7,opt,name=cron,proto3" json:"cron,omitempty"` // для TIME условий
	Timezone      string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	SubConditions []*Condition           `protobuf:"bytes,9,rep,name=sub_conditions,json=subConditions,proto3" json:"sub_conditions,omitempty"`   // для AND/OR/NOT
	ForSeconds    int32                  `protobuf:"varint,10,opt,name=for_seconds,json=forSeconds,proto3" json:"for_seconds,omitempty"`          // условие должно выполняться N секунд
	Metric        string                 `protobuf:"bytes,11,opt,name=metric,proto3" json:"metric,omitempty"`                                     // для TELEMETRY условий
	Threshold     float64                `protobuf:"fixed64,12,opt,name=threshold,proto3" json:"threshold,omitempty"`                             // пороговое значение
	Event         string                 `protobuf:"bytes,13,opt,name=event,proto3" json:"event,omitempty"`                                       // для SUN условий ("sunrise", "sunset")
	OffsetMinutes int32                  `protobuf:"varint,14,opt,name=offset_minutes,json=offsetMinutes,proto3" json:"offset_minutes,omitempty"` // смещение для SUN условий
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_automation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{0}
}

func (x *Condition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Condition) GetType() ConditionType {
	if x != nil {
		return x.Type
	}
	return ConditionType_DEVICE_STATE
}

func (x *Condition) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Condition) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *Condition) GetOperator() ComparisonOperator {
	if x != nil {
		return x.Operator
	}
	return ComparisonOperator_EQ
}

func (x *Condition) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Condition) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *Condition) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Condition) GetSubConditions() []*Condition {
	if x != nil {
		return x.SubConditions
	}
	return nil
}

func (x *Condition) GetForSeconds() int32 {
	if x != nil {
		return x.ForSeconds
	}
	return 0
}

func (x *Condition) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *Condition) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Condition) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Condition) GetOffsetMinutes() int32 {
	if x != nil {
		return x.OffsetMinutes
	}
	return 0
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ActionType             `protobuf:"varint,2,opt,name=type,proto3,enum=automation.ActionType" json:"type,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Template      string                 `protobuf:"bytes,6,opt,name=template,proto3" json:"template,omitempty"`               // для NOTIFICATION
	Data          *structpb.Struct       `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`                       // для NOTIFICATION
	Seconds       int32                  `protobuf:"varint,8,opt,name=seconds,proto3" json:"seconds,omitempty"`                // для DELAY
	Url           string                 `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`                         // для WEBHOOK
	Method        string                 `protobuf:"bytes,10,opt,name=method,proto3" json:"method,omitempty"`                  // для WEBHOOK
	Body          *structpb.Struct       `protobuf:"bytes,11,opt,name=body,proto3" json:"body,omitempty"`                      // для WEBHOOK
	SceneId       string                 `protobuf:"bytes,12,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"` // для SCENE
	Actions       []*Action              `protobuf:"bytes,13,rep,name=actions,proto3" json:"actions,omitempty"`                // для PARALLEL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_automation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_DEVICE_COMMAND
}

func (x *Action) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Action) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Action) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Action) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *Action) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Action) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Action) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Action) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Action) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Action) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *Action) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Trigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ConditionType          `protobuf:"varint,2,opt,name=type,proto3,enum=automation.ConditionType" json:"type,omitempty"`
	Cron          string                 `protobuf:"bytes,3,opt,name=cron,proto3" json:"cron,omitempty"`                                             // для TIME
	Timezone      string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`                                     // для TIME
	DeviceId      string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                     // для DEVICE_STATE
	Property      string                 `protobuf:"bytes,6,opt,name=property,proto3" json:"property,omitempty"`                                     // для DEVICE_STATE
	Operator      ComparisonOperator     `protobuf:"varint,7,opt,name=operator,proto3,enum=automation.ComparisonOperator" json:"operator,omitempty"` // для DEVICE_STATE
	Value         *structpb.Value        `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`                                           // для DEVICE_STATE
	Metric        string                 `protobuf:"bytes,9,opt,name=metric,proto3" json:"metric,omitempty"`                                         // для TELEMETRY
	Threshold     float64                `protobuf:"fixed64,10,opt,name=threshold,proto3" json:"threshold,omitempty"`                                // для TELEMETRY
	Event         string                 `protobuf:"bytes,11,opt,name=event,proto3" json:"event,omitempty"`                                          // для SUN
	OffsetMinutes int32                  `protobuf:"varint,12,opt,name=offset_minutes,json=offsetMinutes,proto3" json:"offset_minutes,omitempty"`    // для SUN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_automation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{2}
}

func (x *Trigger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trigger) GetType() ConditionType {
	if x != nil {
		return x.Type
	}
	return ConditionType_DEVICE_STATE
}

func (x *Trigger) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *Trigger) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Trigger) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Trigger) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *Trigger) GetOperator() ComparisonOperator {
	if x != nil {
		return x.Operator
	}
	return ComparisonOperator_EQ
}

func (x *Trigger) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Trigger) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *Trigger) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Trigger) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Trigger) GetOffsetMinutes() int32 {
	if x != nil {
		return x.OffsetMinutes
	}
	return 0
}

type Scenario struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId         string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Enabled        bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Triggers       []*Trigger             `protobuf:"bytes,6,rep,name=triggers,proto3" json:"triggers,omitempty"`
	Conditions     []*Condition           `protobuf:"bytes,7,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Actions        []*Action              `protobuf:"bytes,8,rep,name=actions,proto3" json:"actions,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExecutionCount int32                  `protobuf:"varint,11,opt,name=execution_count,json=executionCount,proto3" json:"execution_count,omitempty"`
	LastExecuted   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_executed,json=lastExecuted,proto3" json:"last_executed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_automation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{3}
}

func (x *Scenario) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scenario) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scenario) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Scenario) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Scenario) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Scenario) GetTriggers() []*Trigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *Scenario) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Scenario) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Scenario) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Scenario) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Scenario) GetExecutionCount() int32 {
	if x != nil {
		return x.ExecutionCount
	}
	return 0
}

func (x *Scenario) GetLastExecuted() *timestamppb.Timestamp {
	if x != nil {
		return x.LastExecuted
	}
	return nil
}

type CreateScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Triggers      []*Trigger             `protobuf:"bytes,4,rep,name=triggers,proto3" json:"triggers,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Actions       []*Action              `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScenarioRequest) Reset() {
	*x = CreateScenarioRequest{}
	mi := &file_automation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScenarioRequest) ProtoMessage() {}

func (x *CreateScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScenarioRequest.ProtoReflect.Descriptor instead.
func (*CreateScenarioRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{4}
}

func (x *CreateScenarioRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScenarioRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateScenarioRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateScenarioRequest) GetTriggers() []*Trigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *CreateScenarioRequest) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *CreateScenarioRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CreateScenarioRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioRequest) Reset() {
	*x = GetScenarioRequest{}
	mi := &file_automation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioRequest) ProtoMessage() {}

func (x *GetScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioRequest.ProtoReflect.Descriptor instead.
func (*GetScenarioRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{5}
}

func (x *GetScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *GetScenarioRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Triggers      []*Trigger             `protobuf:"bytes,5,rep,name=triggers,proto3" json:"triggers,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,6,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Actions       []*Action              `protobuf:"bytes,7,rep,name=actions,proto3" json:"actions,omitempty"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScenarioRequest) Reset() {
	*x = UpdateScenarioRequest{}
	mi := &file_automation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScenarioRequest) ProtoMessage() {}

func (x *UpdateScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScenarioRequest.ProtoReflect.Descriptor instead.
func (*UpdateScenarioRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *UpdateScenarioRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateScenarioRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateScenarioRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateScenarioRequest) GetTriggers() []*Trigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *UpdateScenarioRequest) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *UpdateScenarioRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *UpdateScenarioRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type DeleteScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScenarioRequest) Reset() {
	*x = DeleteScenarioRequest{}
	mi := &file_automation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScenarioRequest) ProtoMessage() {}

func (x *DeleteScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScenarioRequest.ProtoReflect.Descriptor instead.
func (*DeleteScenarioRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *DeleteScenarioRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ExecuteScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DryRun        bool                   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteScenarioRequest) Reset() {
	*x = ExecuteScenarioRequest{}
	mi := &file_automation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteScenarioRequest) ProtoMessage() {}

func (x *ExecuteScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteScenarioRequest.ProtoReflect.Descriptor instead.
func (*ExecuteScenarioRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ExecuteScenarioRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecuteScenarioRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *ExecuteScenarioRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type ActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Result        *structpb.Struct       `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	DurationMs    int32                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_automation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{9}
}

func (x *ActionResult) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionResult) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ActionResult) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ExecuteScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	ScenarioId    string                 `protobuf:"bytes,2,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	ScenarioName  string                 `protobuf:"bytes,3,opt,name=scenario_name,json=scenarioName,proto3" json:"scenario_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "completed", "failed", "partial"
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs    int32                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Trigger       string                 `protobuf:"bytes,8,opt,name=trigger,proto3" json:"trigger,omitempty"` // "manual", "schedule", "event"
	Actions       []*ActionResult        `protobuf:"bytes,9,rep,name=actions,proto3" json:"actions,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,10,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount  int32                  `protobuf:"varint,11,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	Summary       string                 `protobuf:"bytes,12,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteScenarioResponse) Reset() {
	*x = ExecuteScenarioResponse{}
	mi := &file_automation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteScenarioResponse) ProtoMessage() {}

func (x *ExecuteScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteScenarioResponse.ProtoReflect.Descriptor instead.
func (*ExecuteScenarioResponse) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteScenarioResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteScenarioResponse) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ExecuteScenarioResponse) GetScenarioName() string {
	if x != nil {
		return x.ScenarioName
	}
	return ""
}

func (x *ExecuteScenarioResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteScenarioResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ExecuteScenarioResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ExecuteScenarioResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecuteScenarioResponse) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *ExecuteScenarioResponse) GetActions() []*ActionResult {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ExecuteScenarioResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ExecuteScenarioResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *ExecuteScenarioResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ListUserScenariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OnlyEnabled   bool                   `protobuf:"varint,2,opt,name=only_enabled,json=onlyEnabled,proto3" json:"only_enabled,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserScenariosRequest) Reset() {
	*x = ListUserScenariosRequest{}
	mi := &file_automation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserScenariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserScenariosRequest) ProtoMessage() {}

func (x *ListUserScenariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserScenariosRequest.ProtoReflect.Descriptor instead.
func (*ListUserScenariosRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{11}
}

func (x *ListUserScenariosRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserScenariosRequest) GetOnlyEnabled() bool {
	if x != nil {
		return x.OnlyEnabled
	}
	return false
}

func (x *ListUserScenariosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserScenariosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserScenariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []*Scenario            `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserScenariosResponse) Reset() {
	*x = ListUserScenariosResponse{}
	mi := &file_automation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserScenariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserScenariosResponse) ProtoMessage() {}

func (x *ListUserScenariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserScenariosResponse.ProtoReflect.Descriptor instead.
func (*ListUserScenariosResponse) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserScenariosResponse) GetScenarios() []*Scenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

func (x *ListUserScenariosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUserScenariosResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserScenariosResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_automation_proto protoreflect.FileDescriptor

const file_automation_proto_rawDesc = "" +
	"\n" +
	"\x10automation.proto\x12\n" +
	"automation\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xef\x03\n" +
	"\tCondition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.automation.ConditionTypeR\x04type\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bproperty\x18\x04 \x01(\tR\bproperty\x12:\n" +
	"\boperator\x18\x05 \x01(\x0e2\x1e.automation.ComparisonOperatorR\boperator\x12,\n" +
	"\x05value\x18\x06 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12\x12\n" +
	"\x04cron\x18\a \x01(\tR\x04cron\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12<\n" +
	"\x0esub_conditions\x18\t \x03(\v2\x15.automation.ConditionR\rsubConditions\x12\x1f\n" +
	"\vfor_seconds\x18\n" +
	" \x01(\x05R\n" +
	"forSeconds\x12\x16\n" +
	"\x06metric\x18\v \x01(\tR\x06metric\x12\x1c\n" +
	"\tthreshold\x18\f \x01(\x01R\tthreshold\x12\x14\n" +
	"\x05event\x18\r \x01(\tR\x05event\x12%\n" +
	"\x0eoffset_minutes\x18\x0e \x01(\x05R\roffsetMinutes\"\xb7\x03\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.automation.ActionTypeR\x04type\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x127\n" +
	"\n" +
	"parameters\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x12\x1a\n" +
	"\btemplate\x18\x06 \x01(\tR\btemplate\x12+\n" +
	"\x04data\x18\a \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x18\n" +
	"\aseconds\x18\b \x01(\x05R\aseconds\x12\x10\n" +
	"\x03url\x18\t \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\n" +
	" \x01(\tR\x06method\x12+\n" +
	"\x04body\x18\v \x01(\v2\x17.google.protobuf.StructR\x04body\x12\x19\n" +
	"\bscene_id\x18\f \x01(\tR\asceneId\x12,\n" +
	"\aactions\x18\r \x03(\v2\x12.automation.ActionR\aactions\"\x8e\x03\n" +
	"\aTrigger\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.automation.ConditionTypeR\x04type\x12\x12\n" +
	"\x04cron\x18\x03 \x01(\tR\x04cron\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bproperty\x18\x06 \x01(\tR\bproperty\x12:\n" +
	"\boperator\x18\a \x01(\x0e2\x1e.automation.ComparisonOperatorR\boperator\x12,\n" +
	"\x05value\x18\b \x01(\v2\x16.google.protobuf.ValueR\x05value\x12\x16\n" +
	"\x06metric\x18\t \x01(\tR\x06metric\x12\x1c\n" +
	"\tthreshold\x18\n" +
	" \x01(\x01R\tthreshold\x12\x14\n" +
	"\x05event\x18\v \x01(\tR\x05event\x12%\n" +
	"\x0eoffset_minutes\x18\f \x01(\x05R\roffsetMinutes\"\xf9\x03\n" +
	"\bScenario\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12/\n" +
	"\btriggers\x18\x06 \x03(\v2\x13.automation.TriggerR\btriggers\x125\n" +
	"\n" +
	"conditions\x18\a \x03(\v2\x15.automation.ConditionR\n" +
	"conditions\x12,\n" +
	"\aactions\x18\b \x03(\v2\x12.automation.ActionR\aactions\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12'\n" +
	"\x0fexecution_count\x18\v \x01(\x05R\x0eexecutionCount\x12?\n" +
	"\rlast_executed\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\flastExecuted\"\x96\x02\n" +
	"\x15CreateScenarioRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12/\n" +
	"\btriggers\x18\x04 \x03(\v2\x13.automation.TriggerR\btriggers\x125\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2\x15.automation.ConditionR\n" +
	"conditions\x12,\n" +
	"\aactions\x18\x06 \x03(\v2\x12.automation.ActionR\aactions\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\"N\n" +
	"\x12GetScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xb7\x02\n" +
	"\x15UpdateScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12/\n" +
	"\btriggers\x18\x05 \x03(\v2\x13.automation.TriggerR\btriggers\x125\n" +
	"\n" +
	"conditions\x18\x06 \x03(\v2\x15.automation.ConditionR\n" +
	"conditions\x12,\n" +
	"\aactions\x18\a \x03(\v2\x12.automation.ActionR\aactions\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\"Q\n" +
	"\x15DeleteScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x9e\x01\n" +
	"\x16ExecuteScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructR\acontext\"\xc5\x01\n" +
	"\fActionResult\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12/\n" +
	"\x06result\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x05R\n" +
	"durationMs\"\xe7\x03\n" +
	"\x17ExecuteScenarioResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1f\n" +
	"\vscenario_id\x18\x02 \x01(\tR\n" +
	"scenarioId\x12#\n" +
	"\rscenario_name\x18\x03 \x01(\tR\fscenarioName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x05R\n" +
	"durationMs\x12\x18\n" +
	"\atrigger\x18\b \x01(\tR\atrigger\x122\n" +
	"\aactions\x18\t \x03(\v2\x18.automation.ActionResultR\aactions\x12#\n" +
	"\rsuccess_count\x18\n" +
	" \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\v \x01(\x05R\ffailureCount\x12\x18\n" +
	"\asummary\x18\f \x01(\tR\asummary\"\x87\x01\n" +
	"\x18ListUserScenariosRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fonly_enabled\x18\x02 \x01(\bR\vonlyEnabled\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x96\x01\n" +
	"\x19ListUserScenariosResponse\x122\n" +
	"\tscenarios\x18\x01 \x03(\v2\x14.automation.ScenarioR\tscenarios\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize*]\n" +
	"\rConditionType\x12\x10\n" +
	"\fDEVICE_STATE\x10\x00\x12\b\n" +
	"\x04TIME\x10\x01\x12\r\n" +
	"\tTELEMETRY\x10\x02\x12\a\n" +
	"\x03AND\x10\x03\x12\x06\n" +
	"\x02OR\x10\x04\x12\a\n" +
	"\x03NOT\x10\x05\x12\a\n" +
	"\x03SUN\x10\x06*c\n" +
	"\n" +
	"ActionType\x12\x12\n" +
	"\x0eDEVICE_COMMAND\x10\x00\x12\x10\n" +
	"\fNOTIFICATION\x10\x01\x12\t\n" +
	"\x05DELAY\x10\x02\x12\v\n" +
	"\aWEBHOOK\x10\x03\x12\t\n" +
	"\x05SCENE\x10\x04\x12\f\n" +
	"\bPARALLEL\x10\x05*F\n" +
	"\x12ComparisonOperator\x12\x06\n" +
	"\x02EQ\x10\x00\x12\x06\n" +
	"\x02NE\x10\x01\x12\x06\n" +
	"\x02GT\x10\x02\x12\x06\n" +
	"\x02LT\x10\x03\x12\a\n" +
	"\x03GTE\x10\x04\x12\a\n" +
	"\x03LTE\x10\x052\xf9\x03\n" +
	"\x11AutomationService\x12I\n" +
	"\x0eCreateScenario\x12!.automation.CreateScenarioRequest\x1a\x14.automation.Scenario\x12C\n" +
	"\vGetScenario\x12\x1e.automation.GetScenarioRequest\x1a\x14.automation.Scenario\x12I\n" +
	"\x0eUpdateScenario\x12!.automation.UpdateScenarioRequest\x1a\x14.automation.Scenario\x12K\n" +
	"\x0eDeleteScenario\x12!.automation.DeleteScenarioRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\x0fExecuteScenario\x12\".automation.ExecuteScenarioRequest\x1a#.automation.ExecuteScenarioResponse\x12`\n" +
	"\x11ListUserScenarios\x12$.automation.ListUserScenariosRequest\x1a%.automation.ListUserScenariosResponseB\x1fZ\x1d./proto/automation;automationb\x06proto3"

var (
	file_automation_proto_rawDescOnce sync.Once
	file_automation_proto_rawDescData []byte
)

func file_automation_proto_rawDescGZIP() []byte {
	file_automation_proto_rawDescOnce.Do(func() {
		file_automation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_automation_proto_rawDesc), len(file_automation_proto_rawDesc)))
	})
	return file_automation_proto_rawDescData
}

var file_automation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_automation_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_automation_proto_goTypes = []any{
	(ConditionType)(0),                // 0: automation.ConditionType
	(ActionType)(0),                   // 1: automation.ActionType
	(ComparisonOperator)(0),           // 2: automation.ComparisonOperator
	(*Condition)(nil),                 // 3: automation.Condition
	(*Action)(nil),                    // 4: automation.Action
	(*Trigger)(nil),                   // 5: automation.Trigger
	(*Scenario)(nil),                  // 6: automation.Scenario
	(*CreateScenarioRequest)(nil),     // 7: automation.CreateScenarioRequest
	(*GetScenarioRequest)(nil),        // 8: automation.GetScenarioRequest
	(*UpdateScenarioRequest)(nil),     // 9: automation.UpdateScenarioRequest
	(*DeleteScenarioRequest)(nil),     // 10: automation.DeleteScenarioRequest
	(*ExecuteScenarioRequest)(nil),    // 11: automation.ExecuteScenarioRequest
	(*ActionResult)(nil),              // 12: automation.ActionResult
	(*ExecuteScenarioResponse)(nil),   // 13: automation.ExecuteScenarioResponse
	(*ListUserScenariosRequest)(nil),  // 14: automation.ListUserScenariosRequest
	(*ListUserScenariosResponse)(nil), // 15: automation.ListUserScenariosResponse
	(*structpb.Value)(nil),            // 16: google.protobuf.Value
	(*structpb.Struct)(nil),           // 17: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 19: google.protobuf.Empty
}
var file_automation_proto_depIdxs = []int32{
	0,  // 0: automation.Condition.type:type_name -> automation.ConditionType
	2,  // 1: automation.Condition.operator:type_name -> automation.ComparisonOperator
	16, // 2: automation.Condition.value:type_name -> google.protobuf.Value
	3,  // 3: automation.Condition.sub_conditions:type_name -> automation.Condition
	1,  // 4: automation.Action.type:type_name -> automation.ActionType
	17, // 5: automation.Action.parameters:type_name -> google.protobuf.Struct
	17, // 6: automation.Action.data:type_name -> google.protobuf.Struct
	17, // 7: automation.Action.body:type_name -> google.protobuf.Struct
	4,  // 8: automation.Action.actions:type_name -> automation.Action
	0,  // 9: automation.Trigger.type:type_name -> automation.ConditionType
	2,  // 10: automation.Trigger.operator:type_name -> automation.ComparisonOperator
	16, // 11: automation.Trigger.value:type_name -> google.protobuf.Value
	5,  // 12: automation.Scenario.triggers:type_name -> automation.Trigger
	3,  // 13: automation.Scenario.conditions:type_name -> automation.Condition
	4,  // 14: automation.Scenario.actions:type_name -> automation.Action
	18, // 15: automation.Scenario.created_at:type_name -> google.protobuf.Timestamp
	18, // 16: automation.Scenario.updated_at:type_name -> google.protobuf.Timestamp
	18, // 17: automation.Scenario.last_executed:type_name -> google.protobuf.Timestamp
	5,  // 18: automation.CreateScenarioRequest.triggers:type_name -> automation.Trigger
	3,  // 19: automation.CreateScenarioRequest.conditions:type_name -> automation.Condition
	4,  // 20: automation.CreateScenarioRequest.actions:type_name -> automation.Action
	5,  // 21: automation.UpdateScenarioRequest.triggers:type_name -> automation.Trigger
	3,  // 22: automation.UpdateScenarioRequest.conditions:type_name -> automation.Condition
	4,  // 23: automation.UpdateScenarioRequest.actions:type_name -> automation.Action
	17, // 24: automation.ExecuteScenarioRequest.context:type_name -> google.protobuf.Struct
	17, // 25: automation.ActionResult.result:type_name -> google.protobuf.Struct
	18, // 26: automation.ExecuteScenarioResponse.started_at:type_name -> google.protobuf.Timestamp
	18, // 27: automation.ExecuteScenarioResponse.completed_at:type_name -> google.protobuf.Timestamp
	12, // 28: automation.ExecuteScenarioResponse.actions:type_name -> automation.ActionResult
	6,  // 29: automation.ListUserScenariosResponse.scenarios:type_name -> automation.Scenario
	7,  // 30: automation.AutomationService.CreateScenario:input_type -> automation.CreateScenarioRequest
	8,  // 31: automation.AutomationService.GetScenario:input_type -> automation.GetScenarioRequest
	9,  // 32: automation.AutomationService.UpdateScenario:input_type -> automation.UpdateScenarioRequest
	10, // 33: automation.AutomationService.DeleteScenario:input_type -> automation.DeleteScenarioRequest
	11, // 34: automation.AutomationService.ExecuteScenario:input_type -> automation.ExecuteScenarioRequest
	14, // 35: automation.AutomationService.ListUserScenarios:input_type -> automation.ListUserScenariosRequest
	6,  // 36: automation.AutomationService.CreateScenario:output_type -> automation.Scenario
	6,  // 37: automation.AutomationService.GetScenario:output_type -> automation.Scenario
	6,  // 38: automation.AutomationService.UpdateScenario:output_type -> automation.Scenario
	19, // 39: automation.AutomationService.DeleteScenario:output_type -> google.protobuf.Empty
	13, // 40: automation.AutomationService.ExecuteScenario:output_type -> automation.ExecuteScenarioResponse
	15, // 41: automation.AutomationService.ListUserScenarios:output_type -> automation.ListUserScenariosResponse
	36, // [36:42] is the sub-list for method output_type
	30, // [30:36] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_automation_proto_init() }
func file_automation_proto_init() {
	if File_automation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_automation_proto_rawDesc), len(file_automation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_automation_proto_goTypes,
		DependencyIndexes: file_automation_proto_depIdxs,
		EnumInfos:         file_automation_proto_enumTypes,
		MessageInfos:      file_automation_proto_msgTypes,
	}.Build()
	File_automation_proto = out.File
	file_automation_proto_goTypes = nil
	file_automation_proto_depIdxs = nil
}
