// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: integration.proto

package integration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionMode int32

const (
	ExecutionMode_SEQUENTIAL ExecutionMode = 0
	ExecutionMode_PARALLEL   ExecutionMode = 1
)

// Enum value maps for ExecutionMode.
var (
	ExecutionMode_name = map[int32]string{
		0: "SEQUENTIAL",
		1: "PARALLEL",
	}
	ExecutionMode_value = map[string]int32{
		"SEQUENTIAL": 0,
		"PARALLEL":   1,
	}
)

func (x ExecutionMode) Enum() *ExecutionMode {
	p := new(ExecutionMode)
	*p = x
	return p
}

func (x ExecutionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_proto_enumTypes[0].Descriptor()
}

func (ExecutionMode) Type() protoreflect.EnumType {
	return &file_integration_proto_enumTypes[0]
}

func (x ExecutionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionMode.Descriptor instead.
func (ExecutionMode) EnumDescriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{0}
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"` // "turn_on", "turn_off", "set_brightness"
	Parameters    *structpb.Struct       `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"` // 0-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_integration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Command) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SendCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_integration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{1}
}

func (x *SendCommandRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SendCommandRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type SendCommandResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "delivered", "pending", "failed"
	ResponseTimeMs int32                  `protobuf:"varint,3,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Result         *structpb.Struct       `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendCommandResponse) Reset() {
	*x = SendCommandResponse{}
	mi := &file_integration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponse) ProtoMessage() {}

func (x *SendCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponse) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{2}
}

func (x *SendCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendCommandResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendCommandResponse) GetResponseTimeMs() int32 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *SendCommandResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SendCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchSendCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	Mode          ExecutionMode          `protobuf:"varint,2,opt,name=mode,proto3,enum=integration.ExecutionMode" json:"mode,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSendCommandsRequest) Reset() {
	*x = BatchSendCommandsRequest{}
	mi := &file_integration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendCommandsRequest) ProtoMessage() {}

func (x *BatchSendCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendCommandsRequest.ProtoReflect.Descriptor instead.
func (*BatchSendCommandsRequest) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{3}
}

func (x *BatchSendCommandsRequest) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *BatchSendCommandsRequest) GetMode() ExecutionMode {
	if x != nil {
		return x.Mode
	}
	return ExecutionMode_SEQUENTIAL
}

func (x *BatchSendCommandsRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type BatchSendCommandsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Results         []*CommandResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	OverallSuccess  bool                   `protobuf:"varint,2,opt,name=overall_success,json=overallSuccess,proto3" json:"overall_success,omitempty"`
	TotalDurationMs int32                  `protobuf:"varint,3,opt,name=total_duration_ms,json=totalDurationMs,proto3" json:"total_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchSendCommandsResponse) Reset() {
	*x = BatchSendCommandsResponse{}
	mi := &file_integration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendCommandsResponse) ProtoMessage() {}

func (x *BatchSendCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendCommandsResponse.ProtoReflect.Descriptor instead.
func (*BatchSendCommandsResponse) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{4}
}

func (x *BatchSendCommandsResponse) GetResults() []*CommandResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchSendCommandsResponse) GetOverallSuccess() bool {
	if x != nil {
		return x.OverallSuccess
	}
	return false
}

func (x *BatchSendCommandsResponse) GetTotalDurationMs() int32 {
	if x != nil {
		return x.TotalDurationMs
	}
	return 0
}

type CommandResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ResponseTimeMs int32                  `protobuf:"varint,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Result         *structpb.Struct       `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_integration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandResult) GetResponseTimeMs() int32 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *CommandResult) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Metrics       []string               `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTelemetryRequest) Reset() {
	*x = ReadTelemetryRequest{}
	mi := &file_integration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTelemetryRequest) ProtoMessage() {}

func (x *ReadTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTelemetryRequest.ProtoReflect.Descriptor instead.
func (*ReadTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{6}
}

func (x *ReadTelemetryRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReadTelemetryRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ReadTelemetryRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ReadTelemetryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Values         map[string]float64     `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ResponseTimeMs int32                  `protobuf:"varint,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadTelemetryResponse) Reset() {
	*x = ReadTelemetryResponse{}
	mi := &file_integration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTelemetryResponse) ProtoMessage() {}

func (x *ReadTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTelemetryResponse.ProtoReflect.Descriptor instead.
func (*ReadTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{7}
}

func (x *ReadTelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadTelemetryResponse) GetValues() map[string]float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ReadTelemetryResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ReadTelemetryResponse) GetResponseTimeMs() int32 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *ReadTelemetryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDeviceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatusRequest) Reset() {
	*x = GetDeviceStatusRequest{}
	mi := &file_integration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatusRequest) ProtoMessage() {}

func (x *GetDeviceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceStatusRequest) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeviceStatusRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DeviceStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Online          bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	State           *structpb.Struct       `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	LastSeen        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	SignalStrength  int32                  `protobuf:"varint,5,opt,name=signal_strength,json=signalStrength,proto3" json:"signal_strength,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,6,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceStatus) Reset() {
	*x = DeviceStatus{}
	mi := &file_integration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatus) ProtoMessage() {}

func (x *DeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatus.ProtoReflect.Descriptor instead.
func (*DeviceStatus) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceStatus) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *DeviceStatus) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *DeviceStatus) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *DeviceStatus) GetSignalStrength() int32 {
	if x != nil {
		return x.SignalStrength
	}
	return 0
}

func (x *DeviceStatus) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

var File_integration_proto protoreflect.FileDescriptor

const file_integration_proto_rawDesc = "" +
	"\n" +
	"\x11integration.proto\x12\vintegration\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb4\x01\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x127\n" +
	"\n" +
	"parameters\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\"c\n" +
	"\x12SendCommandRequest\x12.\n" +
	"\acommand\x18\x01 \x01(\v2\x14.integration.CommandR\acommand\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x05R\ttimeoutMs\"\xb8\x01\n" +
	"\x13SendCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12(\n" +
	"\x10response_time_ms\x18\x03 \x01(\x05R\x0eresponseTimeMs\x12/\n" +
	"\x06result\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x9b\x01\n" +
	"\x18BatchSendCommandsRequest\x120\n" +
	"\bcommands\x18\x01 \x03(\v2\x14.integration.CommandR\bcommands\x12.\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1a.integration.ExecutionModeR\x04mode\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"\xa6\x01\n" +
	"\x19BatchSendCommandsResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.integration.CommandResultR\aresults\x12'\n" +
	"\x0foverall_success\x18\x02 \x01(\bR\x0eoverallSuccess\x12*\n" +
	"\x11total_duration_ms\x18\x03 \x01(\x05R\x0ftotalDurationMs\"\xd1\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x05R\x0eresponseTimeMs\x12/\n" +
	"\x06result\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"l\n" +
	"\x14ReadTelemetryRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\ametrics\x18\x02 \x03(\tR\ametrics\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"\xae\x02\n" +
	"\x15ReadTelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12F\n" +
	"\x06values\x18\x02 \x03(\v2..integration.ReadTelemetryResponse.ValuesEntryR\x06values\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x05R\x0eresponseTimeMs\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"5\n" +
	"\x16GetDeviceStatusRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\xff\x01\n" +
	"\fDeviceStatus\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12-\n" +
	"\x05state\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05state\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12'\n" +
	"\x0fsignal_strength\x18\x05 \x01(\x05R\x0esignalStrength\x12)\n" +
	"\x10firmware_version\x18\x06 \x01(\tR\x0ffirmwareVersion*-\n" +
	"\rExecutionMode\x12\x0e\n" +
	"\n" +
	"SEQUENTIAL\x10\x00\x12\f\n" +
	"\bPARALLEL\x10\x012\xf5\x02\n" +
	"\x12IntegrationService\x12P\n" +
	"\vSendCommand\x12\x1f.integration.SendCommandRequest\x1a .integration.SendCommandResponse\x12b\n" +
	"\x11BatchSendCommands\x12%.integration.BatchSendCommandsRequest\x1a&.integration.BatchSendCommandsResponse\x12V\n" +
	"\rReadTelemetry\x12!.integration.ReadTelemetryRequest\x1a\".integration.ReadTelemetryResponse\x12Q\n" +
	"\x0fGetDeviceStatus\x12#.integration.GetDeviceStatusRequest\x1a\x19.integration.DeviceStatusB!Z\x1f./proto/integration;integrationb\x06proto3"

var (
	file_integration_proto_rawDescOnce sync.Once
	file_integration_proto_rawDescData []byte
)

func file_integration_proto_rawDescGZIP() []byte {
	file_integration_proto_rawDescOnce.Do(func() {
		file_integration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integration_proto_rawDesc), len(file_integration_proto_rawDesc)))
	})
	return file_integration_proto_rawDescData
}

var file_integration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_integration_proto_goTypes = []any{
	(ExecutionMode)(0),                // 0: integration.ExecutionMode
	(*Command)(nil),                   // 1: integration.Command
	(*SendCommandRequest)(nil),        // 2: integration.SendCommandRequest
	(*SendCommandResponse)(nil),       // 3: integration.SendCommandResponse
	(*BatchSendCommandsRequest)(nil),  // 4: integration.BatchSendCommandsRequest
	(*BatchSendCommandsResponse)(nil), // 5: integration.BatchSendCommandsResponse
	(*CommandResult)(nil),             // 6: integration.CommandResult
	(*ReadTelemetryRequest)(nil),      // 7: integration.ReadTelemetryRequest
	(*ReadTelemetryResponse)(nil),     // 8: integration.ReadTelemetryResponse
	(*GetDeviceStatusRequest)(nil),    // 9: integration.GetDeviceStatusRequest
	(*DeviceStatus)(nil),              // 10: integration.DeviceStatus
	nil,                               // 11: integration.ReadTelemetryResponse.ValuesEntry
	(*structpb.Struct)(nil),           // 12: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 13: google.protobuf.Timestamp
}
var file_integration_proto_depIdxs = []int32{
	12, // 0: integration.Command.parameters:type_name -> google.protobuf.Struct
	1,  // 1: integration.SendCommandRequest.command:type_name -> integration.Command
	12, // 2: integration.SendCommandResponse.result:type_name -> google.protobuf.Struct
	1,  // 3: integration.BatchSendCommandsRequest.commands:type_name -> integration.Command
	0,  // 4: integration.BatchSendCommandsRequest.mode:type_name -> integration.ExecutionMode
	6,  // 5: integration.BatchSendCommandsResponse.results:type_name -> integration.CommandResult
	12, // 6: integration.CommandResult.result:type_name -> google.protobuf.Struct
	11, // 7: integration.ReadTelemetryResponse.values:type_name -> integration.ReadTelemetryResponse.ValuesEntry
	13, // 8: integration.ReadTelemetryResponse.timestamp:type_name -> google.protobuf.Timestamp
	12, // 9: integration.DeviceStatus.state:type_name -> google.protobuf.Struct
	13, // 10: integration.DeviceStatus.last_seen:type_name -> google.protobuf.Timestamp
	2,  // 11: integration.IntegrationService.SendCommand:input_type -> integration.SendCommandRequest
	4,  // 12: integration.IntegrationService.BatchSendCommands:input_type -> integration.BatchSendCommandsRequest
	7,  // 13: integration.IntegrationService.ReadTelemetry:input_type -> integration.ReadTelemetryRequest
	9,  // 14: integration.IntegrationService.GetDeviceStatus:input_type -> integration.GetDeviceStatusRequest
	3,  // 15: integration.IntegrationService.SendCommand:output_type -> integration.SendCommandResponse
	5,  // 16: integration.IntegrationService.BatchSendCommands:output_type -> integration.BatchSendCommandsResponse
	8,  // 17: integration.IntegrationService.ReadTelemetry:output_type -> integration.ReadTelemetryResponse
	10, // 18: integration.IntegrationService.GetDeviceStatus:output_type -> integration.DeviceStatus
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_integration_proto_init() }
func file_integration_proto_init() {
	if File_integration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integration_proto_rawDesc), len(file_integration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_integration_proto_goTypes,
		DependencyIndexes: file_integration_proto_depIdxs,
		EnumInfos:         file_integration_proto_enumTypes,
		MessageInfos:      file_integration_proto_msgTypes,
	}.Build()
	File_integration_proto = out.File
	file_integration_proto_goTypes = nil
	file_integration_proto_depIdxs = nil
}
